const styles = {
  container: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100vh',
    backgroundColor: '#f5f5f5',
    fontFamily: 'Poppins, sans-serif',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '20px',
    borderRadius: '8px',
    backgroundColor: '#fff',
    boxShadow: '0px 4px 12px rgba(0, 0, 0, 0.1)',
    width: '400px',
  },
  header: {
    marginBottom: '20px',
    fontSize: '24px',
  },
  label: {
    alignSelf: 'flex-start',
    marginBottom: '5px',
    fontSize: '14px',
    fontWeight: 'bold',
  },
  input: {
    width: '100%',
    padding: '10px',
    marginBottom: '15px',
    borderRadius: '4px',
    border: '1px solid #ccc',
    fontSize: '14px',
  },
  checkboxContainer: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '20px',
    fontSize: '14px',
  },
  checkbox: {
    marginRight: '10px',
  },
  submitButton: {
    width: '100%',
    padding: '10px',
    marginBottom: '15px',
    backgroundImage: 'linear-gradient(to right, #9b2fff, #ec4899, #f56565)',
    color: '#fff',
    border: 'none',
    borderRadius: '9999px',
    cursor: 'pointer',
    boxShadow: '0px 4px 12px rgba(0, 0, 0, 0.2)',
    transition: 'background-color 0.3s ease, transform 0.2s ease',
  },
  submitButtonHover: {
    backgroundColor: '#444',
    transform: 'scale(1.05)',
  },
  signInText: {
    fontSize: '14px',
    marginBottom: '10px',
  },
  or: {
    fontSize: '12px',
    marginBottom: '15px',
    color: '#aaa',
  },
  googleButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    padding: '10px',
    marginBottom: '10px',
    borderRadius: '4px',
    border: '1px solid #ccc',
    backgroundColor: '#fff',
    cursor: 'pointer',
    fontSize: '14px',
    transition: 'box-shadow 0.3s ease, transform 0.2s ease',
  },
  googleButtonHover: {
    backgroundColor: '#4285F4',
    color: '#fff',
    boxShadow: '0px 4px 12px rgba(0, 0, 0, 0.2)',
    transform: 'scale(1.05)',
  },
  facebookButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    padding: '10px',
    marginBottom: '10px',
    borderRadius: '4px',
    border: '1px solid #ccc',
    backgroundColor: '#fff',
    cursor: 'pointer',
    fontSize: '14px',
    transition: 'box-shadow 0.3s ease, transform 0.2s ease',
  },
  facebookButtonHover: {
    backgroundColor: '#3b5998',
    color: '#fff',
    boxShadow: '0px 4px 12px rgba(0, 0, 0, 0.2)',
    transform: 'scale(1.05)',
  },
  icon: {
    height: '25px',
    width: '25px',
    marginRight: '10px',
  },
};

export default styles;
